package com.hctxsys.entity;
// Generated 2018-5-4 13:25:23 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * YskSchoolPeople generated by hbm2java
 */
@Entity
@Table(name = "ysk_school_people")
public class YskSchoolPeopleEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String addtime;
	private String name;
	private String age;
	private String addres;
	private String image;
	private String content;
	private Integer fans;
	private BigDecimal graded;
	private int numeration;
	private Integer sort;

	public YskSchoolPeopleEntity() {
	}

	public YskSchoolPeopleEntity(String addtime, String name, String image, String content, int numeration) {
		this.addtime = addtime;
		this.name = name;
		this.image = image;
		this.content = content;
		this.numeration = numeration;
	}

	public YskSchoolPeopleEntity(String addtime, String name, String age, String addres, String image, String content,
			Integer fans, BigDecimal graded, int numeration, Integer sort) {
		this.addtime = addtime;
		this.name = name;
		this.age = age;
		this.addres = addres;
		this.image = image;
		this.content = content;
		this.fans = fans;
		this.graded = graded;
		this.numeration = numeration;
		this.sort = sort;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "addtime", nullable = false)
	public String getAddtime() {
		return this.addtime;
	}

	public void setAddtime(String addtime) {
		this.addtime = addtime;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "age")
	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	@Column(name = "addres")
	public String getAddres() {
		return this.addres;
	}

	public void setAddres(String addres) {
		this.addres = addres;
	}

	@Column(name = "image", nullable = false)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "fans")
	public Integer getFans() {
		return this.fans;
	}

	public void setFans(Integer fans) {
		this.fans = fans;
	}

	@Column(name = "graded", precision = 4, scale = 1)
	public BigDecimal getGraded() {
		return this.graded;
	}

	public void setGraded(BigDecimal graded) {
		this.graded = graded;
	}

	@Column(name = "numeration", nullable = false)
	public int getNumeration() {
		return this.numeration;
	}

	public void setNumeration(int numeration) {
		this.numeration = numeration;
	}

	@Column(name = "sort")
	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

}
